// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csjmvgskogwznwglkkjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzam12Z3Nrb2d3em53Z2xra2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzQzNTUsImV4cCI6MjA2NTU1MDM1NX0.GtNx5ikIKrryTAAAu6rp2wrJVmVdX5Nqc8edgm1JMwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);